insert into municipios(municipio, idDepartamento) values('Cáceres', 1700);
insert into municipios(municipio, idDepartamento) values('Caucasia', 1700);
insert into municipios(municipio, idDepartamento) values('El Bagre', 1700);
insert into municipios(municipio, idDepartamento) values('Nechí', 1700);
insert into municipios(municipio, idDepartamento) values('Tarazá', 1700);
insert into municipios(municipio, idDepartamento) values('Zaragoza', 1700);
insert into municipios(municipio, idDepartamento) values('Caracolí', 1700);
insert into municipios(municipio, idDepartamento) values('Maceo', 1700);
insert into municipios(municipio, idDepartamento) values('Puerto Berrío', 1700);
insert into municipios(municipio, idDepartamento) values('Puerto Nare', 1700);
insert into municipios(municipio, idDepartamento) values('Puerto Triunfo', 1700);
insert into municipios(municipio, idDepartamento) values('Yondó', 1700);
insert into municipios(municipio, idDepartamento) values('Amalfi', 1700);
insert into municipios(municipio, idDepartamento) values('Anorí', 1700);
insert into municipios(municipio, idDepartamento) values('Cisneros', 1700);
insert into municipios(municipio, idDepartamento) values('Remedios', 1700);
insert into municipios(municipio, idDepartamento) values('San Roque', 1700);
insert into municipios(municipio, idDepartamento) values('Santo Domingo', 1700);
insert into municipios(municipio, idDepartamento) values('Segovia', 1700);
insert into municipios(municipio, idDepartamento) values('Vegachí', 1700);
insert into municipios(municipio, idDepartamento) values('Yalí', 1700);
insert into municipios(municipio, idDepartamento) values('Yolombó', 1700);
insert into municipios(municipio, idDepartamento) values('Angostura', 1700);
insert into municipios(municipio, idDepartamento) values('Belmira', 1700);
insert into municipios(municipio, idDepartamento) values('Briceño', 1700);
insert into municipios(municipio, idDepartamento) values('Campamento', 1700);
insert into municipios(municipio, idDepartamento) values('Carolina del Príncipe', 1700);
insert into municipios(municipio, idDepartamento) values('Donmatías', 1700);
insert into municipios(municipio, idDepartamento) values('Entrerríos', 1700);
insert into municipios(municipio, idDepartamento) values('Gómez Plata', 1700);
insert into municipios(municipio, idDepartamento) values('Guadalupe', 1700);
insert into municipios(municipio, idDepartamento) values('Ituango', 1700);
insert into municipios(municipio, idDepartamento) values('San Andrés de Cuerquia', 1700);
insert into municipios(municipio, idDepartamento) values('San José de la Montaña', 1700);
insert into municipios(municipio, idDepartamento) values('San Pedro de los Milagros', 1700);
insert into municipios(municipio, idDepartamento) values('Santa Rosa de Osos', 1700);
insert into municipios(municipio, idDepartamento) values('Toledo', 1700);
insert into municipios(municipio, idDepartamento) values('Valdivia', 1700);
insert into municipios(municipio, idDepartamento) values('Yarumal', 1700);
insert into municipios(municipio, idDepartamento) values('Abriaquí', 1700);
insert into municipios(municipio, idDepartamento) values('Antioquia', 1700);
insert into municipios(municipio, idDepartamento) values('Anzá', 1700);
insert into municipios(municipio, idDepartamento) values('Armenia', 1700);
insert into municipios(municipio, idDepartamento) values('Buriticá', 1700);
insert into municipios(municipio, idDepartamento) values('Caicedo', 1700);
insert into municipios(municipio, idDepartamento) values('Cañasgordas', 1700);
insert into municipios(municipio, idDepartamento) values('Dabeiba', 1700);
insert into municipios(municipio, idDepartamento) values('Ebéjico', 1700);
insert into municipios(municipio, idDepartamento) values('Frontino', 1700);
insert into municipios(municipio, idDepartamento) values('Giraldo', 1700);
insert into municipios(municipio, idDepartamento) values('Heliconia', 1700);
insert into municipios(municipio, idDepartamento) values('Liborina', 1700);
insert into municipios(municipio, idDepartamento) values('Olaya', 1700);
insert into municipios(municipio, idDepartamento) values('Peque', 1700);
insert into municipios(municipio, idDepartamento) values('Sabanalarga', 1700);
insert into municipios(municipio, idDepartamento) values('San Jerónimo', 1700);
insert into municipios(municipio, idDepartamento) values('Sopetrán', 1700);
insert into municipios(municipio, idDepartamento) values('Uramita', 1700);
insert into municipios(municipio, idDepartamento) values('Abejorral', 1700);
insert into municipios(municipio, idDepartamento) values('Alejandría', 1700);
insert into municipios(municipio, idDepartamento) values('Argelia', 1700);
insert into municipios(municipio, idDepartamento) values('El Carmen de Viboral', 1700);
insert into municipios(municipio, idDepartamento) values('Cocorná', 1700);
insert into municipios(municipio, idDepartamento) values('Concepción', 1700);
insert into municipios(municipio, idDepartamento) values('El Peñol', 1700);
insert into municipios(municipio, idDepartamento) values('El Retiro', 1700);
insert into municipios(municipio, idDepartamento) values('El Santuario', 1700);
insert into municipios(municipio, idDepartamento) values('Granada', 1700);
insert into municipios(municipio, idDepartamento) values('Guarne', 1700);
insert into municipios(municipio, idDepartamento) values('Guatapé', 1700);
insert into municipios(municipio, idDepartamento) values('La Ceja', 1700);
insert into municipios(municipio, idDepartamento) values('La Unión', 1700);
insert into municipios(municipio, idDepartamento) values('Marinilla', 1700);
insert into municipios(municipio, idDepartamento) values('Nariño', 1700);
insert into municipios(municipio, idDepartamento) values('Rionegro', 1700);
insert into municipios(municipio, idDepartamento) values('San Carlos', 1700);
insert into municipios(municipio, idDepartamento) values('San Francisco', 1700);
insert into municipios(municipio, idDepartamento) values('San Luis', 1700);
insert into municipios(municipio, idDepartamento) values('San Rafael', 1700);
insert into municipios(municipio, idDepartamento) values('San Vicente', 1700);
insert into municipios(municipio, idDepartamento) values('Sonsón', 1700);
insert into municipios(municipio, idDepartamento) values('Amagá', 1700);
insert into municipios(municipio, idDepartamento) values('Andes', 1700);
insert into municipios(municipio, idDepartamento) values('Angelópolis', 1700);
insert into municipios(municipio, idDepartamento) values('Betania', 1700);
insert into municipios(municipio, idDepartamento) values('Betulia', 1700);
insert into municipios(municipio, idDepartamento) values('Caramanta', 1700);
insert into municipios(municipio, idDepartamento) values('Ciudad Bolívar', 1700);
insert into municipios(municipio, idDepartamento) values('Concordia', 1700);
insert into municipios(municipio, idDepartamento) values('Fredonia', 1700);
insert into municipios(municipio, idDepartamento) values('Hispania', 1700);
insert into municipios(municipio, idDepartamento) values('Jardín', 1700);
insert into municipios(municipio, idDepartamento) values('Jericó', 1700);
insert into municipios(municipio, idDepartamento) values('La Pintada', 1700);
insert into municipios(municipio, idDepartamento) values('Montebello', 1700);
insert into municipios(municipio, idDepartamento) values('Pueblorrico', 1700);
insert into municipios(municipio, idDepartamento) values('Salgar', 1700);
insert into municipios(municipio, idDepartamento) values('Santa Bárbara', 1700);
insert into municipios(municipio, idDepartamento) values('Támesis', 1700);
insert into municipios(municipio, idDepartamento) values('Tarso', 1700);
insert into municipios(municipio, idDepartamento) values('Titiribí', 1700);
insert into municipios(municipio, idDepartamento) values('Urrao', 1700);
insert into municipios(municipio, idDepartamento) values('Valparaíso', 1700);
insert into municipios(municipio, idDepartamento) values('Venecia', 1700);
insert into municipios(municipio, idDepartamento) values('Apartadó', 1700);
insert into municipios(municipio, idDepartamento) values('Arboletes', 1700);
insert into municipios(municipio, idDepartamento) values('Carepa', 1700);
insert into municipios(municipio, idDepartamento) values('Chigorodó', 1700);
insert into municipios(municipio, idDepartamento) values('Murindó', 1700);
insert into municipios(municipio, idDepartamento) values('Mutatá', 1700);
insert into municipios(municipio, idDepartamento) values('Necoclí', 1700);
insert into municipios(municipio, idDepartamento) values('San Juan de Urabá', 1700);
insert into municipios(municipio, idDepartamento) values('San Pedro de Urabá', 1700);
insert into municipios(municipio, idDepartamento) values('Turbo', 1700);
insert into municipios(municipio, idDepartamento) values('Vigía del Fuerte', 1700);
insert into municipios(municipio, idDepartamento) values('Barbosa', 1700);
insert into municipios(municipio, idDepartamento) values('Bello', 1700);
insert into municipios(municipio, idDepartamento) values('Caldas', 1700);
insert into municipios(municipio, idDepartamento) values('Copacabana', 1700);
insert into municipios(municipio, idDepartamento) values('Envigado', 1700);
insert into municipios(municipio, idDepartamento) values('Girardota', 1700);
insert into municipios(municipio, idDepartamento) values('Itagüí', 1700);
insert into municipios(municipio, idDepartamento) values('La Estrella', 1700);
insert into municipios(municipio, idDepartamento) values('Medellín', 1700);
insert into municipios(municipio, idDepartamento) values('Sabaneta', 1700);
